cp ../devserver/WarThunder/aces.vromfs.bin .
cp ../devserver/WarThunder/ui/atlases.vromfs.bin .
cp ../devserver/WarThunder/char.vromfs.bin .
cp ../devserver/WarThunder/game.vromfs.bin .
cp ../devserver/WarThunder/gui.vromfs.bin .
cp ../devserver/WarThunder/ui/images.vromfs.bin .
cp ../devserver/WarThunder/lang.vromfs.bin .
cp ../devserver/WarThunder/mis.vromfs.bin .
cp ../devserver/WarThunder/cache/binary.2.22.0/regional.vromfs.bin .
cp ../devserver/WarThunder/ui/tex.vromfs.bin .
cp ../devserver/WarThunder/wwdata.vromfs.bin .
