cp "../SteamLibrary/steamapps/common/War Thunder/aces.vromfs.bin" .
cp "../SteamLibrary/steamapps/common/War Thunder/ui/atlases.vromfs.bin" .
cp "../SteamLibrary/steamapps/common/War Thunder/char.vromfs.bin" .
cp "../SteamLibrary/steamapps/common/War Thunder/game.vromfs.bin" .
cp "../SteamLibrary/steamapps/common/War Thunder/gui.vromfs.bin" .
cp "../SteamLibrary/steamapps/common/War Thunder/ui/images.vromfs.bin" .
cp "../SteamLibrary/steamapps/common/War Thunder/lang.vromfs.bin" .
cp "../SteamLibrary/steamapps/common/War Thunder/mis.vromfs.bin" .
cp "../SteamLibrary/steamapps/common/War Thunder/cache/binary.2.23.0/regional.vromfs.bin" .
cp "../SteamLibrary/steamapps/common/War Thunder/ui/tex.vromfs.bin" .
cp "../SteamLibrary/steamapps/common/War Thunder/webUi.vromfs.bin" .
cp "../SteamLibrary/steamapps/common/War Thunder/wwdata.vromfs.bin" .
